Prevent from build break with new support library.
The definition of androidx.preference.PreferenceGroup.findPreference() will be changed from:
  public Preference findPreference(CharSequence key)
to:
  public <T extends Preference> T findPreference(CharSequence key)

And this will cause a new build breaks such as:
  packages/apps/EmergencyInfo/tests/unit/src/com/android/emergency/edit/EditInfoActivityTest.java:84: error: reference to that is ambiguous
  assertWithMessage(key).that(medicalInfoParent.findPreference(key)).isNull();
  ^
  both method <E,M>that(Multiset<E>) in TestVerb and method that(Table<?,?,?>) in TestVerb match
  where E,M are type-variables:
  E extends Object declared in method <E,M>that(Multiset<E>)
  M extends Multiset<E> declared in method <E,M>that(Multiset<E>)

Bug: 121008515
Test: make EmergencyInfoUnitTests
Change-Id: Ia27b7cff7b9475bfab92bcb8710054fbec0c11c5